package client;

import javax.swing.*;
import java.awt.*;

public class GUI {
    private JTable resultTable;
    private JPanel contentPanel;
    private JComboBox sqlSelect;

    public static void callGui() {
        JFrame frame = new JFrame("GUI");
        frame.setContentPane(new GUI().contentPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPanel = new JPanel();
        contentPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        resultTable = new JTable();
        resultTable.setFillsViewportHeight(false);
        contentPanel.add(resultTable, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        sqlSelect = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("Ausgabe auswählen...");
        defaultComboBoxModel1.addElement("Temperaturdaten");
        defaultComboBoxModel1.addElement("Sensoren- & Herstellerdaten");
        defaultComboBoxModel1.addElement("Sensoren- & Temperaturdaten");
        defaultComboBoxModel1.addElement("Temperatur- & Sensor- & Herstellerdaten");
        defaultComboBoxModel1.addElement("Letzten 10 Temperaturdaten");
        defaultComboBoxModel1.addElement("Letzten 10 Temperaturdaten absteigend nach Datum");
        defaultComboBoxModel1.addElement("Höchste Temperatur je Sensor");
        defaultComboBoxModel1.addElement("Durchschnitt je Sensor");
        sqlSelect.setModel(defaultComboBoxModel1);
        contentPanel.add(sqlSelect, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(917, 30), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPanel;
    }

}
