package client;

import javax.swing.*;
import java.awt.*;

/*
    HIER kannst du dich austoben, Lucas :)

    Ich habe schonmal etwas vorbereitet,
    du kannst das aber auch gerne anders machen
 */

public class GUIOld extends JFrame {

    private final int WIDTH = 800;
    private final int HEIGHT = 500;

    private final String TITLE = "Temperatur-Client";
    private JButton anzeigeAllesButton;
    private JButton anzeigeButton;
    private JButton button3;

    public GUIOld() {
        initGUI();
        addComponents();
    }

    private void initGUI() {
        setSize(WIDTH, HEIGHT);
        setLocationRelativeTo(null);
        setTitle(TITLE);
        setResizable(false);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    private void addComponents() {
        // Das hier sind nur Beispiele
        JButton btnShowTemps = new JButton("Temperaturdaten");
        JButton btnShowSensors = new JButton("Sensordaten");
        JButton btnShowAverage = new JButton("Durchschnittstemperaturen");

        // Es muss noch ein passendes Layout hinzugefügt werden
        this.add(btnShowTemps);
        this.add(btnShowSensors);
        this.add(btnShowAverage);
    }

    public void display() {
        setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    }
}
